package cliente;

public enum Lugar {
	VenticincoDeMayo("25 de Mayo"),
	Tres_de_febrero("3 de febrero"),
	A_alsina("A. Alsina"),
	A_Gonzales_Chaves("A Gónzalez Cháves"),
	Agus_verdes("Aguas Verdes"),
	Alberti("Alberti"),
	Arrecifes("Arrecifes"),
	Ayacucho("Ayacucho"),
	Azul("Azul"),
	Bahia_blanca("Bahía Blanca"),
	Balcarce("Balcarce"),
	Baradero("Baradero"),
	Benito_juarez("Benito Juárez"),
	Berisso("Berisso"),
	Bolivar("Bolívar"),
	Bragado("Bragrado"),
	Brandsen("Brandsen"),
	Campana("Campana"),
	Canuelas("Cañuelas"),
	Capilla_senior("Capilla del Señor"),
	Capitan_sarmiento("Capitán Sarmiento"),
	Carapachay("Carapachay"),
	Carhue("Carhue"),
	Carilo("Cariló"),
	Carlos_Casares("Carlos casares"),
	Carlos_tejedor("Carlos Tejedor"),
	Carmen_de_Areco("Carmen de Areco"),
	Carmen_de_patagones("Carmen de Patagones"),
	Castelli("Castelli"),
	Chacabuco("Chacabuco"),
	Chascomus("Chascomús"),
	Chivilcoy("Chivilcoy"),
	Colon("Colón"),
	Coronel_dorrego("Coronel Dorrego"),
	Coronel_pringles("Coronel Pringles"),
	Coronel_rosales("Coronel Rosales"),
	Coronel_suarez("Coronel Suarez"),
	Costa_azul("Costa Azul"),
	Costa_chica("Costa Chica"),
	Costa_del_este("Costa del Este"),
	Costa_esmeralda("Costa Esmeralda"),
	Daireaux("Daireaux"),
	Darregueira("Darregueira"),
	Del_viso("Del Viso"),
	Dolores("Dolores"),
	Don_torcuato("Don Torcuato"),
	Ensenada("Ensenada"),
	Escobar("Escobar"),
	Exaltacion_de_la_cruz("Exaltación de la Cruz"),
	Florentino_ameghino("Florentino Ameghino"),
	Garin("Garín"),
	Gral_Alvarado("Gral. Alvarado"),
	Gral_Alvear("Gral. Alvear"),
	Gral_arenales("Gral. Arenales"),
	Gral_belgrano("Gral. Belgrano"),
	Gral_guido("Gral. Guido"),
	Gral_lamadrid("Gral. Lamadrid"),
	Gral_las_heras("Gral. Las Heras"),
	Gral_lavalle("Gral. Lavalle"),
	Gral_madariaga("Gral. Madariaga"),
	Gral_pacheco("Gral. Pacheco"),
	Gral_paz("Gral. Paz"),
	Gral_pinto("Gral. Pinto"),
	Gral_Pueyrredon("Gral. Pueyrredón"),
	Gral_rodriguez("Gral. Rodríguez"),
	Gral_viamonte("Gral. Viamonte"),
	Gral_villegas("Gral. Villegas"),
	Guamini("Guaminí"),
	Guernica("Guernica"),
	Hipolito_yrigoyen("Hipólito Yrigoyen"),
	Maschwitz("Ing. Maschwitz"),
	Junin("Junín"),
	La_plata("La Plata"),
	Laprida("Laprida"),
	Las_flores("Las Flores"),
	Las_toninas("Las Toninas"),
	Leandro_alem("Leandro N. Alem"),
	Lincoln("Lincoln"),
	Loberia("Loberia"),
	Lobos("Lobos"),
	Cardales("Los Cardales")	,
	Los_toldos("Los Toldos"),
	Lucila_del_mar("Lucila del Mar"),
	Loma_verde("Loma verde"),
	Lujan("Luján"),
	Magdalena("Magdalena")	,
	Maipu("Maipú"),
	Mar_chiquita("Mar Chiquita"),
	Mar_de_ajo("Mar de Ajó"),
	Mar_de_las_pampas("Mar de las Pampas"),
	Mar_del_Plata("Mar del plata"),
	Mar_del_tuyo("Mar del Tuyú"),
	Marcos_Paz("Marcos paz")	,
	Mercedes("Mercedes"),
	Miramar("Miramar"),
	Monte("Monte"),
	Monte_Hermoso("Monte hermoso"),
	Munro("Munro"),
	Navarro("Navarro"),
	Necochea("Necochea"),
	Olavarria("Olavarría"),
	Partido_de_la_Costa("Partido de la costa"),
	Pehuajo("Pehuajó"),
	Pellegrini("Pellegrini")	,
	Pergamino("Pergamino"),
	Pigue("Pigüé"),
	Pila("Pila")	,
	Pilar("Pilar"),
	Pinamar("Pinamar"),
	Pinar_del_Sol("Pinar del sol"),
	Polvorines("Polvorines"),
	Pte_peron("Pte. Perón"),
	Puana("Puána"),
	Punta_Indio("Punta indio"),
	Ramallo("Ramallo"),
	Rauch("Rauch"),
	Rivadavia("Rivadavia"),
	Rojas("Rojas"),
	Roque_perez("Roque Pérez"),
	Saavedra("Saavedra (Provincia)"),
	Saladillo("Saladillo"),
	Salliquelo("Salliqueló"),
	Salto("Salto"),
	San_andres_de_giles("San Andrés de Giles"),
	San_antonio_de_areco("San Antonio de Areco"),
	San_Antonio_de_Padua("San Antonio de Padua"),
	San_Bernardo("San Bernando"),
	San_Cayetano("San Cayetano"),
	San_clemente_del_tuyu("San Clemente del Tuyú"),
	San_Nicolas("San Nicolás (Provincia)"),
	San_Pedro("San Pedro"),
	San_Vicente("San Vicente"),
	Santa_Teresita("Santa Teresita"),
	Suipacha("Suipacha"),
	Tandil("Tandil"),
	Tapalque("Tapalqué"),
	Tordillo("Tordillo"),
	Tornquist("Tornquist"),
	Trenque_Lauquen("Trenque Lauquen"),
	Tres_Lomas("Tres Lomas"),
	Villa_Gesell("Villa Gesel"),
	Villarino("Villarino"),
	Zarate("Zárate"),
	Once_de_Septiembre("11 de Septiembre"),
	Veinte_de_Junio("20 de Junio"),
	Veiticinco_de_Mayo("25 de Mayo"),
	Acassuso("Acassuso"),
	Adrogue("Adrogué"),
	Aldo_bonzi("Aldo Bonzi"),
	Area_Reserva_Cinturon_Ecologico("Área Reserva Cinturón Ecológico"),
	Avellaneda("Avellaneda"),
	Banfield("Banfield"),
	Barrio_Parque("Barrio parque"),
	Barrio_Santa_Teresita("Barrio Santa Teresita"),
	Beccar("Beccar"),
	Bella_vista("Bella Vista"),
	Berazategui("Berazategui"),
	Bernal_Este("Bernal Este"),
	Bernal_Oeste("Bernal Oeste"),
	Billinghurst("Billinghurst"),
	Boulogne("Boulogne"),
	Burzaco("Burzaco"),
	Caseros("Caseros"),
	Castelar("Castelar"),
	Churruca("Churruca"),
	Ciudad_Evita("Ciudad Evita"),
	Ciudad_Madero("Ciudad Madero"),
	Ciudadela("Ciudadela"),
	Claypole("Claypole"),
	Crucecita("Crucecita"),
	Dock_Sud("Dock sud"),
	Don_Bosco("Don Bosco"),
	Don_Orione("Don oriente"),
	El_Jaguel("El Jagüel"),
	El_Libertador("El libertador"),
	El_Palomar("El palomar"),
	El_Tala("El tala"),
	El_trebol("El Trébol"),
	Ezeiza("Ezeiza"),
	Ezpeleta("Ezpeleta"),
	Florencio_Varela("Florencio Varela"),
	Florida("Florida"),
	Francisco_Alvarez("Francisco Álvarez"),
	Gerli("Gerli"),
	Glew("Glew"),
	Gonzalez_catan("González Catán"),
	Gral_Lamadrid("Gral. Lamadrid"),
	Grand_bourg("Grand Bourg"),
	Gregorio_de_la_Ferrere("Gregorio de Laferrere"),
	Guillermo_enrique_hudson("Guillermo Enrique Hudson"),
	Haedo("Haedo"),
	Hurlingham("Hurlingham"),
	Ing_Sourdeaux("Ing. Sourdeaux"),
	Isidro_Casanova("Isidro casanova"),
	Ituzaingo("Ituzaingó"),
	Jose_c_paz("José C. Paz"),
	Jose_ingenieros("José Ingenieros"),
	Jose_marmol("José Marmol"),
	La_Lucila("La Lucila"),
	La_Reja("La reja"),
	La_Tablada("La Tablada"),
	Lanus("Lanús"),
	Llavallol("Lavallol"),
	Loma_Hermosa("Loma Hermosa")	,
	Lomas_de_Zamora("Lomas de Zamora"),
	Lomas_del_Millon("Lomas del millon"),
	Lomas_del_Mirador("Lomas del mirador"),
	Longchamps("Longchamps"),
	Los_Polvorines("Los polvorines"),
	Luis_guillon("Luis Guillón"),
	Malvinas_Argentinas("Malvinas Argentinas"),
	Martin_coronado("Martín Coronado"),
	Martinez("Martínez"),
	Merlo("Merlo"),
	Ministro_Rivadavia("Ministro Rivadavia"),
	Monte_Chingolo("Monte chingolo"),
	Monte_Grande("Monte Grande"),
	Moreno("Moreno"),
	Moron("Morón"),
	Muniz("Muñiz"),
	Olivos("Olivos"),
	Pablo_nogues("Pablo Nogués"),
	Pablo_podesta("Pablo Podestá"),
	Paso_del_rey("Paso del Rey"),
	Pereyra("Pereyra"),
	Pineiro("Piñeiro"),
	Platanos("Plátanos"),
	Pontevedra("Pontevedra"),
	Quilmes("Quilmes"),
	Rafael_calzada("Rafael Calzada"),
	Rafael_castilla("Rafael Castilla"),
	Ramos_mejia("Ramos Mejía"),
	Ranelagh("Ranelagh"),
	Remedios_de_escalada("Remedios de Escalada"),
	Saenz_pena("Sáenz Peña"),
	San_antonio_de_padua("San Antonio de Padua"),
	San_fernando("San Fernando"),
	San_francisco_Solano("San Francisco Solano"),
	San_isidro("San Isidro"),
	San_jose("San José"),
	San_justo("San Justo"),
	San_martin("San Martín"),
	San_Miguel("San Miguel"),
	Santos_Lugares("Santos Lugares"),
	Sarandi("Sarandí"),
	Sourigues("Sourigues"),
	Tapiales("Tapiales"),
	Temperley("Temperley"),
	Tigre("Tigre"),
	Tortuguitas("Tortuguitas"),
	Tristan_suerez("Tristán Suárez"),
	Trujui("Trujui"),
	Turdera("Turdera"),
	Valentina_alsina("Valentín Alsina"),
	Vicente_lopez("Vicente López"),
	Villa_adelina("Villa Adelina"),
	Villa_ballester("Villa Ballester"),
	Villa_Bosch("Villa Bosch"),
	Villa_caraza("Villa Caraza"),
	Villa_Celina("Villa Celina"),
	Villa_Centenario("Villa centenario"),
	Villa_de_mayo("Villa de Mayo"),
	Villa_diamante("Villa Diamante"),
	Villa_dominico("Villa Domínico"),
	Villa_espania("Villa España"),
	Villa_fiorito("Villa Fiorito"),
	Villa_guillermina("Villa Guillermina"),
	Villa_insuperable("Villa Insuperable"),
	Villa_jose_leon_suarez("Villa José León Suárez"),
	Villa_La_Florida("Villa la florida"),
	Villa_luzuriaga("Villa Luzuriaga"),
	Villa_martelli("Villa Martelli"),
	Villa_obrera("Villa Obrera"),
	Villa_progreso("Villa Progreso"),
	Villa_Raffo("Villa_Roffo"),
	Villa_sarmiento("Villa Sarmiento"),
	Villa_Tesei("Villa Tesei"),
	Villa_Udaondo("Villa udaondo"),
	Virrey_del_pino("Virrey del Pino"),
	Wilde("Wilde"),
	William_morris("William Morris"),
	Agronomia("Agronomía"),
	Almagro("Almagro"),
	Balvanera("Balvanera"),
	Barracas("Barracas"),
	Belgrano("Belgrano"),
	La_boca("La boca"),
	Boedo("Boedo"),
	Caballito("Caballito"),
	Chacarita("Chacarita"),
	Coghlan("Coghlan"),
	Colegiales("Colegiales"),
	Constitucion("Constitución"),
	Flores("Flores"),
	Floresta("Floresta"),
	La_Paternal("La paternal"),
	Liniers("Liniers"),
	Mataderos("Mataderos"),
	Monserrat("Monserrat"),
	Monte_Castro("Monte castro"),
	Nueva_Pompeya("Nueva Pompeya"),
	Nunez("Núñez"),
	Palermo("Palermo"),
	Parque_Avellaneda("Parque Avellaneda"),
	Parque_Chacabuco("Parque_chacabuco"),
	Parque_Chas("Parque chas"),
	Parque_Patricios("Parque Patricios"),
	Puerto_Madero("Puerto Madero"),
	Recoleta("Recoleta"),
	Retiro("Retiro"),
	Barrio_Saavedra("Barrio Saavedra (CABA)"),
	San_cristobal("San Cristóbal"),
	Barrio_San_Nicolas("San Nicolás (CABA)"),
	San_Telmo("San Telmo"),
	Velez_sarsfield("Vélez Sársfield"),
	Versalles("Versalles"),
	Villa_Crespo("Villa Crespo")	,
	Villa_del_parque("Villa del Parque"),
	Villa_Devoto("Villa Devoto"),
	Villa_Gral_Mitre("Villa Gral Mitre"),
	Villa_Lugano("Villa Lugano"),
	Villa_Luro("Villa Luro"),
	Villa_ortuzar("Villa Ortúzar"),
	Villa_pueyrredon("Villa Pueyrredón"),
	Villa_Real("Villa Real"),
	Villa_Riachuelo("Villa Riachuelo"),
	Villa_Santa_Rita("Villa Santa Rita"),
	Villa_Soldati("Villa Soldati"),
	Villa_Urquiza("Villa Urquiza");
	
	private String nombre;
	
	
	private Lugar(String n)
	{
		this.nombre = n;
	}
}
